### ISSUE TITLE
Switch from Mockserver to Mockserver-Neolight

### ISSUE THREAD

**Issue by twitnic** [xdev-software/mockserver-neolight#200]
### Checklist

- [x] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/mockserver-neolight/issues) or [closed](https://github.com/xdev-software/mockserver-neolight/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

I try to switch from old abandoned mock server to this repo.

In the old Docker-Projekt I do this:

```
  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - '8080:8080'
    environment:
      MOCKSERVER_SERVER_PORT: 8080
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - './docker/mockserver:/config:ro'
```

How could I "mount" /config/initializerJson.json in Neolight?

In this file, I have defined, requests and responses ...

Thanks you all!
